// APIWatch — Share & Export utilities
// Zero backend. 100% browser-native.

// ── URL SHARING ───────────────────────────────────────────────────────────────

export function encodePayloads(a, b) {
  try {
    return btoa(encodeURIComponent(JSON.stringify({ a, b })));
  } catch {
    return null;
  }
}

export function decodePayloads(encoded) {
  try {
    return JSON.parse(decodeURIComponent(atob(encoded)));
  } catch {
    return null;
  }
}

export function buildShareURL(a, b) {
  const encoded = encodePayloads(a, b);
  if (!encoded) return null;
  const base = `${window.location.origin}${window.location.pathname}`;
  return { url: `${base}#diff=${encoded}`, sizeKB: (encoded.length / 1024).toFixed(1) };
}

export function loadFromURL() {
  const hash = window.location.hash;
  if (!hash.startsWith('#diff=')) return null;
  return decodePayloads(hash.slice(6));
}

// ── EXPORTS ───────────────────────────────────────────────────────────────────

export function exportAsJSON(diffs, summary) {
  const report = {
    tool: 'APIWatch',
    generated: new Date().toISOString(),
    summary,
    changes: diffs,
  };
  downloadBlob(JSON.stringify(report, null, 2), `apiwatch-diff-${Date.now()}.json`, 'application/json');
}

export function exportAsMarkdown(changelog, summary) {
  const md = [
    '# API Changelog',
    `> Generated by APIWatch on ${new Date().toLocaleDateString()}`,
    '',
    '## Summary',
    `- **Added:** ${summary?.added ?? 0} keys`,
    `- **Removed:** ${summary?.removed ?? 0} keys`,
    `- **Changed:** ${summary?.changed ?? 0} values`,
    `- **Type Changes:** ${summary?.typeChanged ?? 0} fields`,
    '',
    '## Changes',
    '',
    changelog || '_No AI changelog generated._',
  ].join('\n');
  downloadBlob(md, `apiwatch-changelog-${Date.now()}.md`, 'text/markdown');
}

function downloadBlob(content, filename, type) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text) {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback for non-HTTPS
    const el = document.createElement('textarea');
    el.value = text;
    document.body.appendChild(el);
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);
    return true;
  }
}

// ── HISTORY (localStorage) ────────────────────────────────────────────────────

const HISTORY_KEY = 'apiwatch_history';
const MAX_ENTRIES = 10;

export function saveToHistory(a, b, diffs) {
  try {
    const prev = getHistory();
    const firstPath = diffs[0]?.path || 'empty';
    const entry = {
      id: Date.now(),
      title: `${firstPath} · ${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}`,
      preview: diffs.slice(0, 3).map(d => d.path),
      changeCount: diffs.length,
      a,
      b,
    };
    const updated = [entry, ...prev].slice(0, MAX_ENTRIES);
    localStorage.setItem(HISTORY_KEY, JSON.stringify(updated));
    return updated;
  } catch {
    return [];
  }
}

export function getHistory() {
  try {
    return JSON.parse(localStorage.getItem(HISTORY_KEY) || '[]');
  } catch {
    return [];
  }
}

export function clearHistory() {
  localStorage.removeItem(HISTORY_KEY);
}
